### ISSUE TITLE
vec_xfer_vui128t_2_uint128() is missing

### ISSUE THREAD

**Issue by tuliom** [open-power-sdk/pveclib#127]
PR #120 started using function `vec_xfer_vui128t_2_uint128()` but it isn't available yet, causing build errors during make check:

```
testsuite/arith128_test_i128.c:10068:3: error: AltiVec argument passed to unprototyped function
10068 |   i  = vec_xfer_vui128t_2_uint128 (vi);
      |   ^

testsuite/arith128_test_i128.c:10076:3: error: AltiVec argument passed to unprototyped function
10076 |   i  = vec_xfer_vui128t_2_uint128 (vi);
      |   ^
```

The complete log is available at: https://travis-ci.org/github/tuliom/pveclib/jobs/745960103

**Comment by munroesj52** [comment]
Sorry, you need to apply #121
https://github.com/open-power-sdk/pveclib/pull/121 to fix this issue.
Assumed they would be applied in a timely manner, but then pulls went weeks
without review.

It is hard to make standalone pull requests at this point.

**Comment by munroesj52** [comment]
Committed #121 which resolves this issue.
