### ISSUE TITLE
AltiVec portable implementation

### ISSUE THREAD

**Issue by domalb** [open-power-sdk/pveclib#171]
Hi all,
I open this issue as discussion, please forgive me if this is not appropriate.

I'm currently working on porting software that initially did run  on a PowerPC based CPU.
The C code base contains many direct AltiVec intrinsics, which does not compile for x86_64 and ARM64 architectures of our target platforms.
Rewriting those calls is complex, so our strategy is to implement a port of AltiVec instructions in plain C. In scalar first, and SSE/NEON in a second step.
Would anybody have knowledge of such an existing implementation available?

My underqstanding of `pveclib` is that it does not handle that need, but I thought people involved here would be the best who could provide me some help.

Regards

Domenico Albani

**Comment by ThinkOpenly** [comment]
GCC contains the opposite of what you seek: x86 intrinsics mapped to VSX, up through parts of SSE 4.2. This may or may not be helpful. I don't think Arm has the same -- although I do see an "mmintrin.h" file for Arm, I don't see any others.

For C implementations, it might be helpful to look at the RTL (pseudocode) in the Power ISA document, Book I, Chapters 6 and 7.

**Comment by munroesj52** [comment]
As Paul points out, there is no universal vector intrinsic translator. 

Each effort tends to be a platform support team's effort ro help customers who show a sudden interest in their platform/architecture. But have old software for another architecture.

You may find that the [Vector Intrinsics Porting Guide ](https://files.openpower.foundation/s/7FSEcPrjPH3xmp3) covers some of the issues you will  encounter. For example: Altivec support generic intrinsics (ie vec_add(() where the compiler generated instruction depends on the operand type. Intel intrinsic names are type specific. You will need some auxiary type definitions/casts to manage this.

I have not looked at ARM64.

Also GCC supports some [Vector Extentsions](https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Vector-Extensions.html#Vector-Extensions) that may work across target.

**Comment by munroesj52** [comment]
Closed as outside the scope of PVECLIB
