### ISSUE TITLE
Failed to build with GCC 13

### ISSUE THREAD

**Issue by tuliom** [open-power-sdk/pveclib#173]
pveclib's master branch is failing to build with GCC 13 from Fedora 38, e.g.:

```
In file included from /src/pveclib/src/testsuite/vec_pwr10_dummy.c:37:
/src/pveclib/src/pveclib/vec_f128_ppc.h: In function ‘vec_all_isfinitef128’:
/src/pveclib/src/pveclib/vec_f128_ppc.h:4694:3: error: invalid parameter combination for AltiVec intrinsic ‘__builtin_vec_scalar_test_data_class’
 4694 |   return !scalar_test_data_class (f128, 0x70);
      |   ^~~~~~
/src/pveclib/src/pveclib/vec_f128_ppc.h: In function ‘vec_all_isinff128’:
/src/pveclib/src/pveclib/vec_f128_ppc.h:4726:3: error: invalid parameter combination for AltiVec intrinsic ‘__builtin_vec_scalar_test_data_class’
 4726 |   return scalar_test_data_class (f128, 0x30);
      |   ^~~~~~
```

**Comment by munroesj52** [comment]
Does it only fail for power10? I would expect the same failure for power9. If not I would think compiler bug.

Also it would be nice is gcc would tell me which parameter it does not like. 

GCC 13 is AT16.0?

**Comment by munroesj52** [comment]
Looks like AT16.0 is GCC12... I suspect there will be no AT17.0

Is Travis-CI still running? Otherwise I will have to install/upgrade one of my PowerKVM instances to Fedora 38. I find that fresh Fedora releases are ... flaky.

**Comment by tuliom** [comment]
> Is Travis-CI still running?

No, I never succeeded.
I will take a look if I can find another CI to be used.

> Otherwise I will have to install/upgrade one of my PowerKVM instances to Fedora 38. I find that fresh Fedora releases are ... flaky.

Another option is to use containers. I've been using them even on x86_64 with surprising results when emulating ppc64le.

This is what I run on my x86_64 machine in order to share `$HOME/src` and `$HOME/tmp` as `/src` and `/build` respectively:

```
$ podman run -it --rm --arch=ppc64le --mount=type=bind,source=$HOME/src,destination=/src --mount=type=bind,source=$HOME/tmp,destination=/build fedora:38-ppc64le bash
```

Notice this container will be automatically destroyed after you leave the command line.

**Comment by tuliom** [comment]
> Does it only fail for power10? I would expect the same failure for power9. If not I would think compiler bug.

No. I reproduced this on a Power9 system emulated by QEMU.

> GCC 13 is AT16.0?

No. That would be AT 17.0.
I do see some movements here: https://github.com/advancetoolchain/advance-toolchain/tree/master/configs/17.0
It looks like that AT 17.0 is being prepared. @er-1 might have more details.

**Comment by munroesj52** [comment]
Ok this is fix upstream. 

But GCC13 applies -fnolax-vector-conversions default. So vector __bool __int128 and vector __int128 are not the same!

Clang-15 has the same problem (may be worse).

Either have to go in and add the type casts or apply -flax-vector-conversions to the compiles. Can't add this to configure because I went out of my way to apply (more appropriate) options for -mcpu=power9/10 library builds. 

Will have to think about this.

**Comment by munroesj52** [comment]
> No. I reproduced this on a Power9 system emulated by QEMU.

What version of QEMU are you using?

I have had no luck with QEMU for Power9/10. Too many (VMX/VSX) instructions are not supported.

But I am stuck for now at Ubuntu 20.04 LTS and Fedora 36. 

It seems that the next upgrade breaks the SDK. Between the Java Swing requiring JDK v8 and the IBM JDK being back-level the SDK tends to lock-up or crash. Frustrating. 

I have played with replacing the IBM JDK with the OpenJDK V8. Mixed results. Looking at CLion to replace SDK. But any time spent fixing the SDK or learning a new one delays PVECLIB work.

**Comment by er-1** [comment]
> > GCC 13 is AT16.0?
> 
> No. That would be AT 17.0. 

Right.

> I do see some movements here: https://github.com/advancetoolchain/advance-toolchain/tree/master/configs/17.0 It looks like that AT 17.0 is being prepared. @er-1 might have more details.

AT 17.0 will be released in the beginning of September. It'll support Debian 12, Ubuntu 22.04, RHEL 9 and SLES 15.
Currently (July), it's the beta phase, some packages aren't ready yet.

**Comment by munroesj52** [comment]
Thanks!

**Comment by tuliom** [comment]
> What version of QEMU are you using?

Version 7.0.

> I have had no luck with QEMU for Power9/10. Too many (VMX/VSX) instructions are not supported.

I wouldn't be surprised if I've been lucky.
Although I noticed that QEMU is not emulating /proc/cpuinfo as it does for the other architectures.

**Comment by munroesj52** [comment]
Some more questions:
- Which source was this master?
- How was this configured?

**Comment by tuliom** [comment]
I had reproduced this with both `master` and the code from PR #172.
But it seems that PR #174 already fixed this.

I had configured it without extra arguments.

Thanks!

**Comment by munroesj52** [comment]
Yes this is likely the fix that did it:

#ifdef __float128
// Can assume GCC 7 or later so ...
// That version defines __ieee128 internally and
// #defines __float128 to __ieee128, so both are defined
// Define __binary128 so both GCC and CLang can use a single type
#define __binary128 __ieee128
#else
// Assume GCC 6 or earlier
// So the compiler defines __float128 only
typedef __float128 __binary128;
typedef __float128 __ieee128;
#endif

The old code tried to typedef __float128 over __ieee128. The compiler did
not like this.
