### ISSUE TITLE
GCC 5 and 6 compilers fail (ICE) when compiling the pveclib test case arith128_test_i128.c

### ISSUE THREAD

**Issue by munroesj52** [open-power-sdk/pveclib#2]
GCC 5 and 6 compilers fail (ICE) when compiling the pveclib test case arith128_test_i128.c in function test_4b.../../pveclib/src/testsuite/arith128_test_i128.c: In function ‘test_4b’:
../../pveclib/src/testsuite/arith128_test_i128.c:1029:1: internal compiler error: in simplify_binary_operation_1, at simplify-rtx.c:3707
 }
 ^
0x98b8ff simplify_binary_operation_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/simplify-rtx.c:3707
0x98bd2d simplify_binary_operation(rtx_code, machine_mode, rtx_def*, rtx_def*)
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/simplify-rtx.c:2069
0x695253 cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1842
0x69660e cselib_expand_value_rtx_cb(rtx_def*, bitmap_head*, int, rtx_def* (*)(rtx_def*, bitmap_head*, int, void*), void*)
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1550
0xbc01e5 vt_expand_var_loc_chain
        /build/at10.0_Ubuntu16_x86_64
0xbc01e5 vt_expand_loc_callback
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8492
0x695162 cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1703
0x694efc cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1741
0x69660e cselib_expand_value_rtx_cb(rtx_def*, bitmap_head*, int, rtx_def* (*)(rtx_def*, bitmap_head*, int, void*), void*)
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1550
0xbc01e5 vt_expand_var_loc_chain
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8330
0xbc01e5 vt_expand_loc_callback
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8492
0x695162 cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1703
0x694efc cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x
0x69660e cselib_expand_value_rtx_cb(rtx_def*, bitmap_head*, int, rtx_def* (*)(rtx_def*, bitmap_head*, int, void*), void*)
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1550
0xbc01e5 vt_expand_var_loc_chain
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8330
0xbc01e5 vt_expand_loc_callback
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8492
0x695162 cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:170386_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:17410x69660e cselib_expand_value_rtx_cb(rtx_def*, bitmap_head*, int, rtx_def* (*)(rtx_def*, bitmap_head*, int, void*), void*)
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1550
0xbbfe9b vt_expand_loc_callback
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/var-tracking.c:8428
0x6950c1 cselib_expand_value_rtx_1
        /build/at10.0_Ubuntu16_x86_64-ppc64le/21/at10.0-6.ubuntu-16_x86_64_ppc64le/sources/gcc/gcc/cselib.c:1668
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.

**Comment by munroesj52** [comment]
This effects AT9 and AT10. It does not occur with AT11 and GCC 7.

**Comment by munroesj52** [comment]
This should be reported to the GCC team. But in the meantime we can work around this by splitting test_4b into two smaller functions.

**Comment by munroesj52** [comment]
For now we should just split arith128_test_i128.c (test_4b) into the two smaller functions: test_4b and test_4b1. This requires updates to arith128_test_i128.h (extern for test_4b1) and pveclib_test.c (add call to test_4b1)

**Comment by ThinkOpenly** [comment]
Fixed by pull #5
