### ISSUE TITLE
Some files are missing -mcpu

### ISSUE THREAD

**Issue by tuliom** [open-power-sdk/pveclib#82]
Some C files make usage of POWER8 built-ins without passing `-mcpu=power8`
to the compiler, e.g.:
```
In file included from src/pveclib/vec_int64_ppc.h:26,
                 from src/pveclib/vec_int128_ppc.h:28,
                 from src/tipowof10.c:23:
src/pveclib/vec_int32_ppc.h: In function ‘vec_mulesw’:
src/pveclib/vec_int32_ppc.h:736:3: note: builtin ‘__builtin_vec_mule’ requires builtin ‘__builtin_altivec_vmulesw’
  736 |   res = vec_mule (a, b);
      |   ^~~
```

This works well on powerpc64le because GCC defaults to `-mcpu=power8`.
However, when building for powerpc64, GCC defaults to `-mcpu=power4`, causing these errors.

I've noticed this with the following files:
 - src/testsuite/vec_int128_dummy.c
 - src/tipowof10.c
 - src/testsuite/vec_int64_dummy.c

**Comment by munroesj52** [comment]
Ya that's not going to work. pveclib requires <altivec.h> which is disabled for power4/5.

For technical reasons (the f32/f64/128 ops need instructions (like xxpermdi) introduced with VSX), so pveclib is only tested for powerr7/8/9. Power7 is the only supported/tested BE configuration. Technically it may be possible to provide portions (some includes but not all) of pveclib for older VMX only (power6/970) machines but that would be a lot more work. Work I am not going to even think about until there is actual demand.

So can you restrict pveclib to ppc64le AT builds? That guarantees a power8/VSX minimum. Supporting the RHEL7 BE configurations would have to be a special case.

**Comment by munroesj52** [comment]
I stated these restrictions and intent in the documentation: https://munroesj52.github.io/ in section "POWER Vector Library Intrinsic headers"

**Comment by tuliom** [comment]
> So can you restrict pveclib to ppc64le AT builds?

Yes, but isn't it better for everyone if these tests and dummy files had their build parameters fixed, e.g. in src/Makefile.am:

```
vec_dummy_CFLAGS += -mcpu=power8
```

This is the same solution being used by other libraries that use `altivec.h`, e.g.:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/powerpc/powerpc64/fpu/multiarch/Makefile;h=63191cfbec20ec2122f046b3ea8aed515470dcd1;hb=refs/heads/tuliom/libmvec#l57

If you ever decide to support an older processor (I'm not asking for it  ;-) ) you could change this value later.

**Comment by munroesj52** [comment]
But that would prevent someone from using pveclib on RHEL7 BE with AT9/10?

It needs to be conditional or overridable from configure

**Comment by tuliom** [comment]
> But that would prevent someone from using pveclib on RHEL7 BE with AT9/10?

Good point.
In that case, isn't it better to test for `defined _ARCH_PWR8` too? e.g. https://github.com/open-power-sdk/pveclib/blob/master/src/pveclib/vec_int64_ppc.h#L1438

**Comment by munroesj52** [comment]
The code is already full of #ifdef __ARCH_PWR* and will compiler correctly for -mcpu-power7 BE and -mcpu=power7/8/9 for LE.
The problem is RHEL7? defaulted to power4. No vectors, no build.

What is required is to guarantee a compiler default of at least power7 for BE and power8 LE.
Forcing hard power7 for LE platforms would be wrong. Forcing -mcpu=

Provide a configure override of build on BE platforms for at least -mcpu=power7. Or have the configure/makefile check the compiler default and force it up to power7.

**Comment by munroesj52** [comment]
Sorry I have been distracted by ... life.

Any way if you want to set a floor for pveclib, the simplest is to provide:
  CFLAGS=-m64 -O3 -mcpu=power8
for LE, and
  CFLAGS=-m64 -O3 -mcpu=power7
for BE. On every configure.

I do this for every build and this gets round the immediate problem.

If you want to make this bullet-proof we would have to gen-up a configure test to force a reasonable CFLAGS if the build did not provide. If the builder provides a bad CFLAGS that is their problem. And if they complain then we know someone is actually trying to use pveclib.

In the long run we/I will have to provide ifunc implementation for any dynamic libraries. 

But I am busy with 2048x2048 right now for if you want to propose a patch ...

**Comment by munroesj52** [comment]
ok i now see that even for BE -mcpu=power7 this fails to compile. 

../../pveclib_v1_AT12/src/pveclib/vec_int32_ppc.h:736:3: note: builtin ‘__builtin_vec_mule’ requires builtin ‘__builtin_altivec_vmulesw’
   res = vec_mule (a, b);

The core problem is that PowerISA 2.06B does not have a Vector Multiply even/odd Signed Word. 
It does not have unsigned either but that is handled in the code using multiply unsigned halfword.

So the solution is to take the vec_abs of the inputs then use vec_mul[e|o]uw to generate the product. Then xor the original inputs and shift right signed 31 to get the product sign. Then correct (make negative) the product if needed. Hacker Delight Chapter 8-3 may be helpful.
